# Generated by Django 6.0.2 on 2026-02-23 09:49

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(max_length=1)),
                ('number', models.IntegerField()),
                ('seat_id', models.CharField(blank=True, max_length=5, unique=True)),
                ('booked', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
